name: PPH checker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [
          ubuntu-18.04-clang-4.0
        ]
        include:
          - name: ubuntu-18.04-clang-4.0
            os: ubuntu-18.04
            compiler: clang
            version: "4.0"
    steps:
    - uses: actions/checkout@v2
    - name: Run pph
      run: ./tools/pph.sh
    - name: Check diff
      run: git diff --exit-code
